version: '3.1'

services:
  app:
    image: 'hw_20_docker'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - app
    expose:
      - 8080

  db:
    image: 'mysql:latest'
    container_name: databae
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    ports:
      - '3307:3306'
    expose:
      - 3307
    networks:
      - app

networks:
  app:
    driver: bridge

